### ISSUE TITLE
Java 17 Support

### ISSUE THREAD

**Issue by jabrena** [ContextMapper/context-mapper-dsl#311]
**Is your feature request related to a problem? Please describe.**

I would like to use this library with Java 17

Currently, If I try to execute the examples with Java 17, I receive the following error:

```java
[ERROR] org.contextmapper.standalone.example.ContextMapGeneratorExampleTest.test  Time elapsed: 0.677 s  <<< ERROR!
com.google.inject.internal.util.$ComputationException: com.google.inject.internal.util.$ComputationException: java.lang.ExceptionInInitializerError
        at org.contextmapper.standalone.example.ContextMapGeneratorExampleTest.test(ContextMapGeneratorExampleTest.java:20)
Caused by: com.google.inject.internal.util.$ComputationException: java.lang.ExceptionInInitializerError
        at org.contextmapper.standalone.example.ContextMapGeneratorExampleTest.test(ContextMapGeneratorExampleTest.java:20)
Caused by: java.lang.ExceptionInInitializerError
        at org.contextmapper.standalone.example.ContextMapGeneratorExampleTest.test(ContextMapGeneratorExampleTest.java:20)
Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make protected final java.lang.Class java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain) throws java.lang.ClassFormatError accessible: module java.base does not "opens java.lang" to unnamed module @1e7ba8d9
        at org.contextmapper.standalone.example.ContextMapGeneratorExampleTest.test(ContextMapGeneratorExampleTest.java:20)
```

**Describe the solution you'd like**

The library need to be compatible with Java 17 and Upgrade the pipelines for that JVM version.

**Describe alternatives you've considered**

**Additional context**

**Comment by smsnheck** [comment]
Hi @stefan-ka correct me if I am wrong but 7 days ago the java 17 build ran successfully. When will the 6.7.0 version be released (and integrated in the CLI)?

I am very interested in a java 17 version with the new xtext version. If I can help you out please give me a hint. 

Best

**Comment by smsnheck** [comment]
Good morning @stefan-ka, great to hear that you are planning a release on friday :) 
I appreciate you working on the tool during your free time. 

FYI: I am integrating your tool in my arc42-architecture documentation archetype. Therefore I can wait some days.

**Comment by stefan-ka** [comment]
@jabrena, @smsnheck, the release v6.7.0 of Context Mapper with Java 17 support is now available: https://contextmapper.org/news/2022/12/02/v6.7.0-released/
I will therefore close this issue. If you have any questions, feel free to contact me.

**Comment by jabrena** [comment]
Many thanks @stefan-ka,

I will review the tool again in coming weeks.

Have a good weekend

Juan Antonio
